'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Account
    Public Property ID As Integer
    Public Property UserName As String
    Public Property PassWord As String
    Public Property DisplayName As String

End Class
Partial Public Class Messages
    Public Property ID As Integer
    Public Property Content As String
    Public Property AccountID As String
    Public Property AccountName As String

End Class
Partial Public Class Rooms
    Public Property ID As String
    Public Property Name As String
    Public Property UserAccountId As String

End Class
Partial Public Class sysdiagrams
    Public Property name As String
    Public Property principal_id As Integer
    Public Property diagram_id As Integer
    Public Property version As Nullable(Of Integer)
    Public Property definition As Byte()

End Class
Partial Public Class UserRooms
    Public Property RoomId As String
    Public Property UserId As String
    Public Property Id As String

End Class
