'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ChatEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ChatEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Account() As DbSet(Of Account)
    Public Overridable Property Messages() As DbSet(Of Messages)
    Public Overridable Property Rooms() As DbSet(Of Rooms)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property UserRooms() As DbSet(Of UserRooms)

End Class
